import {
  ExpenseClaim,
  User,
  DepartmentBudget,
  ReimbursementRecord,
} from "@/types/finance";

export const MOCK_USERS: User[] = [
  { id: "u1", name: "Aditya Kumar", email: "aditya@company.com", role: "EMPLOYEE", department: "Engineering", managerId: "u3", avatarInitials: "AK" },
  { id: "u2", name: "Rabil Sheikh", email: "rabil@company.com", role: "FINANCE", department: "Finance & Treasury", avatarInitials: "RS" },
  { id: "u3", name: "Tejasvini Rao", email: "tejasvini@company.com", role: "MANAGER", department: "Engineering", avatarInitials: "TR" },
  { id: "u4", name: "Priya Nair", email: "priya@company.com", role: "EMPLOYEE", department: "Engineering", managerId: "u3", avatarInitials: "PN" },
  { id: "u5", name: "Vikram Singh", email: "vikram@company.com", role: "EMPLOYEE", department: "Sales", managerId: "u3", avatarInitials: "VS" },
];

export const MOCK_CLAIMS: ExpenseClaim[] = [
  {
    id: "CLM-001",
    employeeId: "u1",
    employeeName: "Aditya Kumar",
    employeeDepartment: "Engineering",
    title: "The Oberoi Bengaluru - Client Architecture Sync",
    description: "3-day technical architecture review with enterprise client stakeholders.",
    amount: 6000.00,
    currency: "INR",
    category: "HOTEL",
    paymentMethod: "PERSONAL_CARD",
    merchant: "The Oberoi Grand",
    receiptName: "oberoi_invoice_oct2026.pdf",
    status: "SUBMITTED",
    submittedAt: "2026-10-04T09:30:00Z",
    createdAt: "2026-10-04T08:15:00Z",
    updatedAt: "2026-10-04T09:30:00Z",
    policyViolation: "Nightly accommodation cap exceeded. Standard threshold ₹5,000.",
    policyExceededAmount: 1000.00,
    employeeExceptionReason: "Last-minute booking required due to emergency client migration meeting. No standard rooms available.",
  },
  {
    id: "CLM-002",
    employeeId: "u4",
    employeeName: "Priya Nair",
    employeeDepartment: "Engineering",
    title: "Air India Return Flight - BLR to DEL",
    description: "Direct flight booked for on-site data center security migration.",
    amount: 8500.00,
    currency: "INR",
    category: "TRAVEL",
    paymentMethod: "CORPORATE_CARD",
    merchant: "Air India",
    receiptName: "air_india_boarding_pass.pdf",
    status: "MANAGER_APPROVED",
    submittedAt: "2026-10-02T11:00:00Z",
    createdAt: "2026-10-02T10:00:00Z",
    updatedAt: "2026-10-03T14:20:00Z",
    managerRemark: "Approved. Card charge verified against corporate booking.",
  },
  {
    id: "CLM-003",
    employeeId: "u5",
    employeeName: "Vikram Singh",
    employeeDepartment: "Sales",
    title: "Client Hospitality Dinner - Q4 Prospect",
    description: "Dinner meeting with FinTech executive team.",
    amount: 3200.00,
    currency: "INR",
    category: "MEALS",
    paymentMethod: "PERSONAL_UPI",
    merchant: "Olive Beach Restaurant",
    receiptName: "olive_beach_tax_receipt.jpg",
    status: "SUBMITTED",
    submittedAt: "2026-10-04T18:00:00Z",
    createdAt: "2026-10-04T17:40:00Z",
    updatedAt: "2026-10-04T18:00:00Z",
    isDuplicateWarning: true,
    duplicateDetails: "Potential duplicate: ₹3,200 charged to same merchant within 48h.",
  },
  {
    id: "CLM-004",
    employeeId: "u1",
    employeeName: "Aditya Kumar",
    employeeDepartment: "Engineering",
    title: "JetBrains All Products License Renewal",
    description: "Annual IDE software licenses for the core backend engineering unit.",
    amount: 14500.00,
    currency: "INR",
    category: "SOFTWARE",
    paymentMethod: "PERSONAL_CARD",
    merchant: "JetBrains s.r.o.",
    receiptName: "jetbrains_tax_invoice.pdf",
    status: "FINANCE_APPROVED",
    submittedAt: "2026-09-28T10:00:00Z",
    createdAt: "2026-09-28T09:00:00Z",
    updatedAt: "2026-10-01T15:30:00Z",
    managerRemark: "Essential dev infrastructure. Approved.",
    financeRemark: "Tax invoice validated with GSTIN. Cleared for disbursement.",
  },
  {
    id: "CLM-005",
    employeeId: "u4",
    employeeName: "Priya Nair",
    employeeDepartment: "Engineering",
    title: "Hardware Dongles & USB-C Adapters",
    description: "Field deployment adapters for server racks.",
    amount: 1850.00,
    currency: "INR",
    category: "HARDWARE",
    paymentMethod: "PERSONAL_UPI",
    merchant: "Croma Electronics",
    receiptName: "croma_bill.pdf",
    status: "FINANCE_APPROVED",
    submittedAt: "2026-10-01T12:00:00Z",
    createdAt: "2026-10-01T11:00:00Z",
    updatedAt: "2026-10-02T16:00:00Z",
    isHold: true,
    holdReason: "Awaiting physical GST invoice copy from claimant.",
    heldAt: "2026-10-03T10:15:00Z",
  },
  {
    id: "CLM-006",
    employeeId: "u1",
    employeeName: "Aditya Kumar",
    employeeDepartment: "Engineering",
    title: "Uber Executive Transit - Delhi Airport to HQ",
    description: "Airport transit for late night client arrival.",
    amount: 1250.00,
    currency: "INR",
    category: "TRAVEL",
    paymentMethod: "PERSONAL_UPI",
    merchant: "Uber India",
    receiptName: "uber_ride_receipt.pdf",
    status: "PAID",
    submittedAt: "2026-09-20T22:00:00Z",
    createdAt: "2026-09-20T21:30:00Z",
    updatedAt: "2026-09-25T11:00:00Z",
    paymentReference: "UTR-NEFT-2026-0925-8812",
    disbursedAt: "2026-09-25T11:00:00Z",
    paymentChannel: "Corporate NEFT Clearing",
  },
];

export const MOCK_BUDGETS: DepartmentBudget[] = [
  { id: "b1", name: "Engineering", allocatedAmount: 500000, spentAmount: 314000, currency: "INR", fiscalPeriod: "Q4-2026", thresholdPercent: 80 },
  { id: "b2", name: "Sales & Client Growth", allocatedAmount: 350000, spentAmount: 185000, currency: "INR", fiscalPeriod: "Q4-2026", thresholdPercent: 75 },
  { id: "b3", name: "Operations & Cloud", allocatedAmount: 200000, spentAmount: 162000, currency: "INR", fiscalPeriod: "Q4-2026", thresholdPercent: 85 },
];
